#!/bin/sh
lock() {
    #i3lock -c 90C3D4 -i ~/Pictures/arch_linux_logo.png #~/Pictures/Landscapes/www.dmzwarez.info_Natures_0007.jpg
    sh ~/.config/i3/i3lock
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-nagbar -t warning -m 'Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit' #i3-msg exit
        ;;
    suspend)
        #i3-nagbar -t warning -m 'Do you really want to suspend this session?' -b 'Yes, suspend' 'lock && systemctl suspend' #lock && systemctl suspend
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        i3-nagbar -t warning -m 'Do you really want to reboot your computer?' -b 'Yes, reboot' 'reboot' #systemctl reboot
        ;;
    shutdown)
        i3-nagbar -t warning -m 'Do you really want to shutdown your computer?' -b 'Yes, shutdown' 'poweroff' #systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
