#!/bin/sh
lock() {
    #i3lock -c 90C3D4 -i ~/Pictures/arch_linux_logo.png #~/Pictures/Landscapes/www.dmzwarez.info_Natures_0007.jpg
    sh ~/.config/i3/i3lock
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-nagbar -t warning -m 'Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit' #i3-msg exit
        ;;
    suspend)
        lock 
        systemctl suspend
        ;;
    hibernate)
        lock
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
