#!/bin/bash

if [ -f "$HOME/.config/scripts/dmenucommand" ]; then
    . "$HOME/.config/scripts/dmenucommand"
fi

menu=$(echo -e "Logout\nReboot\nSuspend\nHibernate\nShutdown" | eval $DMENU -p \"Select\")

case "$menu" in
    Logout) i3-msg exit ;;
    Reboot) systemctl reboot ;;
    Suspend) 
        lockscreen -l dim 
        systemctl suspend 
        ;;
    Hibernate) systemctl hibernate ;;
    Shutdown) systemctl poweroff ;;
esac

[ "$menu" == "" ] || ~/.config/polybar/launch.sh
