#!/bin/bash

FOLDER="/tmp"
WALLPAPER="$HOME/.config/wallpaper.png"

DIMSCREEN="$FOLDER/dimscreen.png"
BLURSCREEN="$FOLDER/blurscreen.png"
DIMBLURSCREEN="$FOLDER/dimblurscreen.png"
RESIZED="$FOLDER/resized.png"


L_DIMSCREEN="$FOLDER/l_dimscreen.png"
L_BLURSCREEN="$FOLDER/l_blurscreen.png"
L_DIMBLURSCREEN="$FOLDER/l_dimblurscreen.png"
L_RESIZED="$FOLDER/l_resized.png"

initialize() {
    echo "Generating temporary images for lockscreen..."

    # find your resolution so images can be resized to match your screen resolution
    resolution=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')

    if [ -n "$1" ]; then
        if [ -f "$1" ]; then
            convert "$1" -resize "$resolution""^" -gravity center -extent "$resolution" "$RESIZED"
        else
            echo "File $1 does not exist."
            exit 1
        fi
    else
            convert "$WALLPAPER" -resize "$resolution""^" -gravity center -extent "$resolution" "$RESIZED"
    fi

    convert $RESIZED -blur 0x5 $BLURSCREEN
    convert $RESIZED -fill black -colorize 40% $DIMSCREEN
    convert $DIMSCREEN -blur 0x5 $DIMBLURSCREEN

    # ratio for rectangle to be drawn for time background on lockscreen
    rectangles=" "
    SR=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]*x[0-9][0-9]*[^ ]*')
    for RES in $SR; do
        SRA=(${RES//[x+]/ })
        CX=$((${SRA[2]} + 25))
        CY=$((${SRA[1]} - 30))
        rectangles+="rectangle $CX,$CY $((CX+300)),$((CY-80)) "
    done

    # add transparent rectangle as background for datetime
    convert $RESIZED -draw "fill rgba(0, 0, 0, 0.4) $rectangles" $L_RESIZED
    convert $DIMSCREEN -draw "fill rgba(0, 0, 0, 0.4) $rectangles" $L_DIMSCREEN
    convert $DIMBLURSCREEN -draw "fill rgba(0, 0, 0, 0.4) $rectangles" $L_DIMBLURSCREEN
    convert $BLURSCREEN -draw "fill rgba(0, 0, 0, 0.4) $rectangles" $L_BLURSCREEN
}

lock() {
i3lock -i $1 --timepos="x+140:h-70" \
        --datepos="tx+24:ty+25" \
        --clock --datestr "%m/%d/%Y" \
        --insidecolor=00000000 --ringcolor=ffffffff --line-uses-inside \
        --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
        --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff \
        --ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="x+280:h-70" \
        --radius=20 --ring-width=3 --veriftext="" --wrongtext="" \
        --timecolor="ffffffff" --datecolor="ffffffff"
}


selectlock() {
    case "$1" in
        dim) lock "$L_DIMSCREEN" ;;
        blur) lock "$L_BLURSCREEN" ;;
        dimblur) lock "$L_DIMBLURSCREEN" ;;
        *) lock "$L_RESIZED" ;;
    esac
}

case "$1" in
    -i | --init) initialize ;;
    -u | --update) initialize "$2" ;;
    -l | --lock) selectlock "$2" ;;
    -s | --suspend) 
        selectlock "$2" 
        systemctl suspend 
        ;;
    -b | --hibernate)
        selectlock "$2"
        systemctl hibernate
        ;;
    -w | --wallpaper) 
       case "$2" in
           dim) feh --bg-scale $DIMSCREEN ;;
           blur) feh --bg-scale $BLURSCREEN ;;
           dimblur) feh --bg-scale $DIMBLURSCREEN ;;
           *) feh --bg-scale $RESIZED ;;
       esac
         ;;
    *) lock "$L_RESIZED" ;;
esac

