#!/bin/bash

while [[ -f noname$n ]]; 
do
    n=$((n+1));
done

if [[ -z "$1" ]]; then
    filename="noname$n"
else
    filename="$1"
fi

if [[ -f $filename ]]; then
    st -e vim $filename
else

    echo -e "#!/bin/bash\n\n" > $filename;
    chmod +x $filename;
    st -e vim $filename
fi
