#!/bin/bash

if [ -f "$HOME/.config/scripts/dmenucommand" ]; then
    . "$HOME/.config/scripts/dmenucommand"
fi

prompt=$(echo -e "Yes\nNo" | eval $DMENU -p \"$1\")

if [[ $prompt == "Yes" ]]; then
    exec $2 ;
else
    exit ;
fi

