#!/bin/bash

FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
FONT=$(xrdb -query | grep 'Rofi.font:' | awk -F'font:' '{print $NF}')

DIALOG_RESULT=$(echo -e 'exit i3\nhibernate\nsuspend\nreboot\nshutdown' | rofi -dmenu -font "$FONT" -i -p "[ Computer ] " -hide-scrollbar -tokenize -lines 5 -eh 1 -width 40 -location 8 -xoffset 170 -yoffset 70 -padding 30 -disable-history -color-enabled true -color-window "$BACKGROUND,$BLACK,$BACKGROUND" -color-normal "$BACKGROUND,$FOREGROUND,$BACKGROUND,$BLUE,$BACKGROUND" -color-active "$BACKGROUND,$MAGENTA,$BACKGROUND,$BACKGROUND,$BLUE" -color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND,$BACKGROUND,$BLUE")

echo "This result is : $DIALOG_RESULT"
sleep 1;

case "$DIALOG_RESULT" in
    "exit i3")
        i3-msg exit
        ;;
    hibernate)
        ~/.config/scripts/lockscreen
        systemctl hibernate
        ;;
    suspend)
        ~/.config/scripts/lockscreen
        systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Bad argument"
        exit 2
esac
exit 0
