#!/bin/bash

# set folders
resource="$HOME/.Xresources"
res_theme="$HOME/.themes/colors/"
res_font="$HOME/.themes/fonts/"
tmp_seq="/tmp/sequence"

if [ ! -n "$1" ]; then
    echo "No argument passed."
    exit 1
fi

change_theme() {
    OLD_THEME=$(cat $resource | grep "colors" | awk -F'/' '/[a-z]/{print $NF}' | awk -F'\"' '{print $1}')

    if [ ! -f "$res_theme""$1" ]; then
        echo "Resources for theme \"$1\" not found."
        exit 1
    fi

    sed -i "s/$OLD_THEME/$1/g" "$resource"
}

change_font() {
    OLD_FONT=$(cat $resource | grep "fonts" | awk -F'/' '/[a-z]/{print $NF}' | awk -F'\"' '{print $1}')

    if [ ! -f "$res_font""$1" ]; then
        echo "Font \"$1\" not found."
        exit 1
    fi

    sed -i "s/$OLD_FONT/$1/g" "$resource"
}

preapply() {
    if [ $(pgrep -x dunst) ]; then
        killall dunst
    fi
}

apply() {
    echo "Applying theme..."
    xrdb "$resource"

    echo "Reloading i3..."
    i3-msg restart
    sleep 1

    # get colors
    FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
    BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
    CURSOR=$(xrdb -query | grep 'cursorColor:'| awk '{print $NF}')
    D_BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
    D_RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
    D_GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
    D_YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
    D_BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
    D_MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
    D_CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
    D_WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
    L_BLACK=$(xrdb -query | grep 'color8:'| awk '{print $NF}')
    L_RED=$(xrdb -query | grep 'color9:'| awk '{print $NF}')
    L_GREEN=$(xrdb -query | grep 'color10:'| awk '{print $NF}')
    L_YELLOW=$(xrdb -query | grep 'color11:'| awk '{print $NF}')
    L_BLUE=$(xrdb -query | grep 'color12:'| awk '{print $NF}')
    L_MAGENTA=$(xrdb -query | grep 'color13:'| awk '{print $NF}')
    L_CYAN=$(xrdb -query | grep 'color14:'| awk '{print $NF}')
    L_WHITE=$(xrdb -query | grep 'color15:'| awk '{print $NF}')
    FONT=$(xrdb -query | grep -i 'Dunst.font:'| awk -F'font:' '{print $NF}')
}

postapply() {
    dunst -font "$FONT" -lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$L_BLACK" -nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$D_BLACK" -cb "$D_RED" -cf "$D_WHITE" -cfr "$L_RED" &
}

cast_sequence() {
    sequence="]4;0;$D_BLACK\\]4;1;$D_RED\\]4;2;$D_GREEN\\]4;3;$D_YELLOW\\]4;4;$D_BLUE\\]4;5;$D_MANGENTA\\]4;6;$D_CYAN\\]4;7;$D_WHITE\\]4;8;$L_BLACK\\]4;9;$L_RED\\]4;10;$L_GREEN\\]4;11;$L_YELLOW\\]4;12;$L_BLUE\\]4;13;$L_MAGENTA\\]4;14;$L_CYAN\\]4;15;$L_WHITE\\]10;$FOREGROUND\\]11;$BACKGROUND\\]12;$CURSOR\\]13;$FOREGROUND\\]17;$FOREGROUND\\]19;$BACKGROUND\\]4;232;$BACKGROUND\\[s[1000H[8m]708;$BACKGROUND\\[u]13;$CURSOR\\"

    echo "$sequence" > "$tmp_seq"

    cat "$tmp_seq"
}


while [ "$#" -gt 0 ];
do
case "$1" in
    -f | --font) 
        echo "$2"
        preapply
        change_font "$2" 
        shift 2
        ;;
    -t | --theme) 
        preapply
        change_theme "$2"
        shift 2
        ;;
    *)
        shift
        echo "Bad Argument."
        exit 1
        ;;
esac
done

apply
postapply
cast_sequence
notify-send "Notification" "i3 Reloaded"
