#!/bin/bash

pid1=$(pgrep -x transmission-daemon)
pid2=$(pgrep -x transmission-da)


if [[ ! $pid1 == "" ]]; then
    kill $pid1 ;
    notify-send "Transmission daemon killed!" ;
    exit 2 ;
elif [[ ! $pid2 == "" ]]; then
    kill $pid2 ;
    notify-send "Transmission daemon killed!" ;
    exit 2 ;
else
    transmission-daemon ;
    notify-send "Transmission daemon started." ;
    exit 2 ;
fi

exit 0 ;
