#!/usr/bin/env sh

music()
{
    [ -z "$(mpc status | sed "/^volume:/d")" ] && mpc status | tr '\n' ' ' | sed -e "s/^.*/🎵 stopped/g"

    mpc status | sed "/^volume:/d" | tac | tr '\n' ' ' | cut -d' ' -f4- | awk '/\([0-9]+%\)/{ for (i = 3; i <= NF; i++){a=a$i" "} print "🎵", a"["$1"]"}' | sed "s/\\&/&/g" | tr -d '\n'
}

internet()
{
    signal=$(grep "^\s*w" /proc/net/wireless | awk '{ print "📶", int($3 * 100 / 70) "%" }')

    [ "$(cat /sys/class/net/w*/operstate)" = "down" ] && signal="❎"

    printf '%s %s' "$signal" "$(cat /sys/class/net/e*/operstate | sed "s/down/❎/;s/up/🌐/")" 
}


volume()
{
    volume=$(amixer get Master | tail -n 1 | awk -F'[' '{print $2 }' | tr '%]\n' ' ' | tr -d '[:space:]') || exit

    if [ $volume -gt 65 ]; then
	    icon="🔊"
    elif [ $volume -gt 35 ]; then
	    icon="🔉"
    else
	    icon="🔈"
    fi

    volume=$(echo $volume | sed 's/$/%/')

    [ $(amixer get Master | tail -n 1 | awk -F'[' '{print $3 }' | tr ']\n' ' ') = "off" ] && icon="🔇" && volume=""
	
    printf '%s %s' "$icon" "$volume"
}


backlight()
{
    brightness=$(cat /sys/class/backlight/intel_backlight/brightness) || exit
    max=$(cat /sys/class/backlight/intel_backlight/max_brightness)

    backlight=$(bc -l <<< "$brightness*100/$max")

    if [ $brightness -gt 796 ]; then
	    icon="🌑"
    elif [ $brightness -gt 656 ]; then
	    icon="🌒"
    elif [ $brightness -gt 375 ]; then
	    icon="🌓"
    elif [ $brightness -gt 134 ]; then
	    icon="🌔"
    else
	    icon="🌕"
    fi

    printf '%s %.0f%%' "$icon" "$backlight"
}


battery()
{
    capacity=$(cat /sys/class/power_supply/BAT0/capacity) || exit
    status=$(cat /sys/class/power_supply/BAT0/status)

    [ $capacity -lt 18 ] && warn="❗"
    [ -z "$warn" ] && warn=" "

    [ $status = "Charging" ] && color="$color15" && warn=" " 
	
    [ $status = "Full" ] && color="$color2"

    printf '%s%s%s' "$(echo $status | sed "s/Charging/🔌/;s/Discharging/🔋/;s/Unknown/♻/;s/Full/⚡/")" "$warn" "$(echo $capacity | sed 's/$/%/')"
}

date=$(date +"⏰ %I:%M %p")

echo " $(music)  $(internet)  $(volume)  $(backlight)  $(battery)  $date "
