#!/usr/bin/env sh

[ $(cat /sys/class/power_supply/BAT0/status) = "Charging" ] && exit
[ $(cat /sys/class/power_supply/BAT0/capacity) -lt 15 ] && 
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus &&
dunstify -r 1234 -u critical "Battery critically low!"
