#!/bin/bash

pid=$(pgrep -x transmission-da)

if [[ $pid -ne 0 ]]; then
    kill $pid 
    dunstify -r 2323 "Transmission daemon killed!" & 
    exit 2 
else
    transmission-daemon &
    dunstify -r 2323 "Transmission daemon started." & 
    exit 2 
fi

exit 0 ;
