#!/bin/bash

# Using neovim instead of vim
command -v nvim >/dev/null && alias vim="nvim"

# Colorize commands
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	lla="ls -hla --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	fgrep="fgrep --color=auto" \
	egrep="egrep --color=auto" \
	diff="diff --color=auto"

# Pacman commands
alias \
	upgrade="sudo pacman -Syu" \
	downgrade="sudo pacman -U" \
	pac="sudo pacman" \
	spac="pacman -Ss" \
	dpac="sudo pacman -Rnsdd"

# Paths related
alias \
	xsrc="xrdb $XDG_CONFIG_HOME/Xresources" \
	bsrc="source ~/.bashrc" \
	zsrc="source $XDG_CONFIG_HOME/zsh/.zshrc" \
	ref="shortcuts >/dev/null && source $HOME/.config/shortcutsrc"

# Apps commands
alias \
	starwars="telnet towel.blinkenlights.nl" \
	phps="php -S localhost:8000 -t public/ -d display_errors=1" \
	yt="youtube-dl --add-metadata -i" \
	yta="youtube-dl --add-metadata -xif bestaudio/best" \
	e="$EDITOR" \
	sr="sudo ranger" \
	trc="transmission-remote-cli" \
	ka="killall"

# ----------------------
# Git Aliases
# ----------------------
alias \
	ga='git add' \
	gaa='git add .' \
	gaaa='git add -A' \
	gc='git commit' \
	gcm='git commit -m' \
	gd='git diff' \
	gi='git init' \
	gl='git log' \
	gp='git pull' \
	gpsh='git push' \
	gss='git status -s' \
	gs='echo ""; echo "*********************************************"; echo -e "   DO NOT FORGET TO PULL BEFORE COMMITTING"; echo "*********************************************"; echo ""; git status' \
