#!/bin/sh

eval "$(xres2var)"

# Autostart section
sxhkd &
setwallpaper &
xsetroot -cursor_name left_ptr &
#[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
#pgrep -x panel >/dev/null || panel &
$HOME/.config/polybar/launch.sh &

mainmon=$(xrandr | grep primary | awk '{print $1}')
secmon=$(bspc query --monitors --names | grep -v $mainmon | head -n1)

if [ -n "$secmon" ]; then
	bspc monitor $mainmon -d 1 2 3 4 5
	bspc monitor $secmon -d 6 7 8 9 10
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width            2
bspc config window_gap              10

bspc config split_ratio             0.50
bspc config single_monocle          true
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     true

#### BSPWM coloring ####
bspc config normal_border_color		"$background"
bspc config active_border_color		"$color3"
bspc config focused_border_color	"$color4"
bspc config presel_feedback_color	"$color7"
bspc config urgent_border_color 	"$color1"

### Browsing ###
bspc rule -r "*"
bspc rule -a firefox desktop='^2'
bspc rule -a Brave-browser desktop='^2' follow=off
bspc rule -a Chromium desktop='^2'
bspc rule -a tabbed desktop='^2'
bspc rule -a Google-chrome desktop='^2'
### Coding ###
bspc rule -a Code desktop='^3' follow=off
### Multimedia ###
bspc rule -a Gimp desktop='^4' follow=off
bspc rule -a Inkscape desktop='^4' follow=off
### Recording, Virtualtization ###
bspc rule -a obs desktop='^9'
bspc rule -a 'VirtualBox Manager' desktop='^9'
bspc rule -a 'VirtualBox Machine' desktop='^10'
bspc rule -a Blueberry.py desktop='^10' state=floating
bspc rule -a 'Tor Browser' desktop='^10'
### Window states and behaviour ###
bspc rule -a Screenkey manage=off
bspc rule -a '*:mpvfloat' state=floating
bspc rule -a firefox:Places state=floating
bspc rule -a Zathura state=tiled

numlockx on &
synclient TapButton1=1 &
xautolock -time 10 -locker "lockscreen -l dimblur" &
[ -n "$(pgrep -x picom)" ] && picom &
[ -n "$(pgrep -x dunst)" ] && dunstrun &
[ -n "$(pgrep -x redshift)" ] && redshift &

