#!/usr/bin/env sh

case $BLOCK_BUTTON in
    1) bluetooth toggle &>/dev/null ;;
    2) blueberry &>/dev/null ;;
	3) $TERMINAL -e nmtui &>/dev/null ;;
esac

signal=$(grep "^\s*w" /proc/net/wireless | awk '{ print "📶", int($3 * 100 / 70) "%" }')

if [[ $(bluetooth) = "bluetooth = on" ]]; then
    bluetooth=""
else
    bluetooth=""
fi

[ "$(cat /sys/class/net/w*/operstate)" = "down" ] && signal="❌"

printf '%s %s %s' "$signal" "$(cat /sys/class/net/e*/operstate | sed "s/down/❌/;s/up/🌐/")" "$bluetooth"
