#!/bin/bash

eval $(xres2var)
font=$(xrdb -query | grep 'Dmenu.font:'| awk -F'font:' '{print $NF}')

dmenu -fn "$font" -nb "$background" -nf "$foreground" -sb "$color4" -sf "$background" -i -p "$1" -l "$2"
