#!/bin/bash

# A dmenu recording prompt for my different recording scripts.

# Asks for type of recording and uses one of my three different scripts.
asktype() { \
case $(echo -e "Screencast\nVideo only\nAudio only" | dmenurun "Select recording mode:" 3) in
	Screencast) screencast ;;
	"Audio only") audio ;;
	"Video only") video ;;
esac ;}


# If already running, will ask to end previous recording.

asktoend() { \
response=$(echo -e "No\nYes" | dmenurun "Recording still active. End recording?" 2)
if [[ "$response" = "Yes" ]]; then killall ffmpeg; fi ;}

if (( $(pgrep dmenurecord | wc -l) > 2 )); then
asktoend;
else
asktype;
fi
echo "$response"
