#!/bin/bash

menu=$(echo -e "Logout\nReboot\nSuspend\nHibernate\nShutdown" | dmenurun "Select" 5)

case "$menu" in
    Logout) i3-msg exit ;;
    Reboot) systemctl reboot ;;
    Suspend) 
        lockscreen -l blur 
        systemctl suspend 
        ;;
    Hibernate) 
        lockscreen -l blur
        systemctl hibernate 
        ;;
    Shutdown) systemctl poweroff ;;
esac

