#!/bin/bash

eval $(xres2var)
FONT=$(xrdb -query | grep 'Rofi.font:' | awk -F'font:' '{print $NF}')

DIALOG_RESULT=$(echo -e 'exit i3\nhibernate\nsuspend\nreboot\nshutdown' | rofi -dmenu -font "$FONT" -i -p "[ Computer ] " -hide-scrollbar -tokenize -lines 5 -eh 1 -width 40 -location 8 -xoffset 170 -yoffset 70 -padding 30 -disable-history -color-enabled true -color-window "$background,$color0,$background" -color-normal "$background,$foreground,$background,$color4,$background" -color-active "$background,$color5,$background,$background,$color4" -color-urgent "$background,$color3,$background,$background,$color4")

echo "This result is : $DIALOG_RESULT"
sleep 1;

case "$DIALOG_RESULT" in
    "exit i3")
        i3-msg exit
        ;;
    hibernate)
        ~/.config/scripts/lockscreen
        systemctl hibernate
        ;;
    suspend)
        ~/.config/scripts/lockscreen
        systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Bad argument"
        exit 2
esac
exit 0
