#!/bin/bash

# This is a ffmpeg screencast script that uses pulseaudio or alsa depending on what you've installed

while [[ -f $HOME/Videos/screencast$n.mkv ]]
do
    n=$((n+1))
done

filename="$HOME/Videos/screencast$n.mkv"

# For pulseaudio
cast_pulseaudio()
{
    ffmpeg -y \
    -f x11grab \
    -s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
    -i :0.0 \
    -f alsa -i default \
     -c:v libx264 -r 30 -c:a flac $filename
     #-c:v ffvhuff -r 30 -c:a flac $filename
     #-f pulse -ac 1 -ar 44100 -i default \
}

# For alsa
cast_alsa()
{

    ffmpeg -y \
    -f x11grab \
    -s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
    -i :0.0 \
    -thread_queue_size 1024 \
     -f alsa -ar 44100 -i hw:1 \
     -c:v libx264 -r 30 -c:a flac $filename
     #-c:v ffvhuff -r 30 -c:a flac $filename
}

if [[ $(pgrep -x pulseaudio) ]]; then cast_pulseaudio; else cast_alsa; fi
